# Quiz Quest Native Deployment
# Uses the quiz-quest-app image from Docker Hub without port forwarding

services:
  quiz-quest-native:
    image: yoktian/quiz-quest-app:latest # Change 'mrkazawa' to your Docker Hub username
    container_name: quiz-quest-native
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TEACHER_PASSWORD=${TEACHER_PASSWORD:-admin}
      - SESSION_SECRET=${SESSION_SECRET:-}
      - PORT=3000
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}
    volumes:
      # Mount questions directory for custom quiz content (read-write for question creation)
      - ../questions:/app/questions
      # Optional: persist application data
      - quiz-quest-data:/app/data
    restart: unless-stopped
    networks:
      - quiz-quest-network
    # Resource limits for production stability
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: quiz-quest-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Add SSL certificates for HTTPS
      # - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - quiz-quest-native
    networks:
      - quiz-quest-network
    profiles:
      - with-nginx
    restart: unless-stopped

volumes:
  quiz-quest-data:

networks:
  quiz-quest-network:
    driver: bridge
# Usage Examples:
#
# Standard native deployment:
#   docker-compose -f docker-compose-native.yml up -d
#
# With Nginx reverse proxy (recommended for production):
#   docker-compose -f docker-compose-native.yml --profile with-nginx up -d
#
# With custom teacher password:
#   TEACHER_PASSWORD=ultra-secure-password docker-compose -f docker-compose-native.yml up -d
#
# Access the application:
#   http://localhost:3000 (direct)
#   http://localhost (with Nginx profile)
#
# View logs:
#   docker-compose -f docker-compose-native.yml logs -f
#
# Stop services:
#   docker-compose -f docker-compose-native.yml down
